// <auto-generated />
namespace AspNetGroupBasedPermissions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _201402161844035_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201402161844035_init));
        
        string IMigrationMetadata.Id
        {
            get { return "201601171325202_201402161844035_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
